//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FranchiseName
    {
        public int FranchiseNameId { get; set; }
        public int FranchiseId { get; set; }
        public string Region { get; set; }
        public string Name { get; set; }
        public System.DateTime StartDt { get; set; }
        public Nullable<System.DateTime> EndDt { get; set; }
        public string mod_usr { get; set; }
        public System.DateTime mod_date { get; set; }
    
        public virtual Franchise Franchise { get; set; }
    }
}
