//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FranchisePosition
    {
        public int FranchisePositionId { get; set; }
        public int FranchiseId { get; set; }
        public int PersonId { get; set; }
        public int PositionCodeId { get; set; }
        public System.DateTime StartDt { get; set; }
        public Nullable<System.DateTime> EndDt { get; set; }
        public string mod_usr { get; set; }
        public System.DateTime mod_date { get; set; }
    
        public virtual Franchise Franchise { get; set; }
        public virtual Person Person { get; set; }
        public virtual PositionCode PositionCode { get; set; }
    }
}
