//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhasSportsEntities : DbContext
    {
        public PhasSportsEntities()
            : base("name=PhasSportsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Conference> Conferences { get; set; }
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<GameStatu> GameStatus { get; set; }
        public virtual DbSet<Season> Seasons { get; set; }
        public virtual DbSet<SportsType> SportsTypes { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<ViewAllGame> ViewAllGames { get; set; }
        public virtual DbSet<ViewAllTeamRecordsPerct> ViewAllTeamRecordsPercts { get; set; }
        public virtual DbSet<ViewAllTeamRecordsPerctGamesBehind> ViewAllTeamRecordsPerctGamesBehinds { get; set; }
    }
}
