//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PositionCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PositionCode()
        {
            this.FranchisePositions = new HashSet<FranchisePosition>();
        }
    
        public int PositionCodeId { get; set; }
        public string PositionCode1 { get; set; }
        public string PositionDescrip { get; set; }
        public string SportTypeCode { get; set; }
        public System.DateTime StartDt { get; set; }
        public Nullable<System.DateTime> EndDt { get; set; }
        public string mod_usr { get; set; }
        public System.DateTime mod_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FranchisePosition> FranchisePositions { get; set; }
        public virtual SportType SportType { get; set; }
    }
}
