//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Season
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Season()
        {
            this.FranchiseTeams = new HashSet<FranchiseTeam>();
        }
    
        public int seasonid { get; set; }
        public string SportTypeCode { get; set; }
        public System.DateTime startdate { get; set; }
        public string mod_user { get; set; }
        public System.DateTime mod_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FranchiseTeam> FranchiseTeams { get; set; }
        public virtual SportType SportType { get; set; }
    }
}
