//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SportType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SportType()
        {
            this.Franchises = new HashSet<Franchise>();
            this.FranchiseSportTypes = new HashSet<FranchiseSportType>();
            this.PositionCodes = new HashSet<PositionCode>();
            this.Seasons = new HashSet<Season>();
        }
    
        public string SportTypeCode { get; set; }
        public string SportTypeGroupCode { get; set; }
        public string SportTypeDescrip { get; set; }
        public int SeasonStartMonth { get; set; }
        public string mod_user { get; set; }
        public System.DateTime mod_date { get; set; }
        public string SportTypeShortName { get; set; }
        public Nullable<int> SportStartYear { get; set; }
        public string ParentTypeCode { get; set; }
        public Nullable<int> SportEndYear { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Franchise> Franchises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FranchiseSportType> FranchiseSportTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PositionCode> PositionCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Season> Seasons { get; set; }
        public virtual SportTypeGroup SportTypeGroup { get; set; }
    }
}
