//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllGamesView
    {
        public int SeasonId { get; set; }
        public string SportTypeCode { get; set; }
        public System.DateTime SportStartDate { get; set; }
        public int GameId { get; set; }
        public int HomeFranchiseId { get; set; }
        public string HomeTeam { get; set; }
        public Nullable<int> HomeScore { get; set; }
        public int VisitorFranchiseId { get; set; }
        public string VisitorTeam { get; set; }
        public Nullable<int> VisitorScore { get; set; }
        public System.DateTime GameDtm { get; set; }
        public bool Preseason { get; set; }
        public Nullable<int> PlayoffId { get; set; }
    }
}
