//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllTeamRecordsPerctGamesBehindView
    {
        public int seasonid { get; set; }
        public string SportTypeCode { get; set; }
        public Nullable<int> SportYear { get; set; }
        public string conference { get; set; }
        public string division { get; set; }
        public int franchiseid { get; set; }
        public string team { get; set; }
        public Nullable<int> WINS { get; set; }
        public Nullable<int> LOSES { get; set; }
        public Nullable<int> TIES { get; set; }
        public Nullable<double> PERCT { get; set; }
        public string HOMEREC { get; set; }
        public string AWAYREC { get; set; }
        public Nullable<decimal> GB { get; set; }
    }
}
