//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FranchiseTeam
    {
        public int id { get; set; }
        public int seasonid { get; set; }
        public int franchiseid { get; set; }
        public string div_cd { get; set; }
        public System.DateTime StartDt { get; set; }
        public Nullable<System.DateTime> EndDt { get; set; }
        public string mod_user { get; set; }
        public Nullable<System.DateTime> mod_date { get; set; }
    
        public virtual Franchise Franchise { get; set; }
        public virtual Season Season { get; set; }
    }
}
