//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GameStatEntities : DbContext
    {
        public GameStatEntities()
            : base("name=GameStatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Franchise> Franchises { get; set; }
        public virtual DbSet<FranchiseName> FranchiseNames { get; set; }
        public virtual DbSet<FranchiseOwner> FranchiseOwners { get; set; }
        public virtual DbSet<FranchisePosition> FranchisePositions { get; set; }
        public virtual DbSet<FranchiseSportType> FranchiseSportTypes { get; set; }
        public virtual DbSet<FranchiseTeam> FranchiseTeams { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<PositionCode> PositionCodes { get; set; }
        public virtual DbSet<Season> Seasons { get; set; }
        public virtual DbSet<SportType> SportTypes { get; set; }
        public virtual DbSet<SportTypeGroup> SportTypeGroups { get; set; }
        public virtual DbSet<Stadium> Stadia { get; set; }
        public virtual DbSet<StadiumSurfaceCode> StadiumSurfaceCodes { get; set; }
        public virtual DbSet<StateCode> StateCodes { get; set; }
        public virtual DbSet<AllTeamRecordsPerctGamesBehindView> AllTeamRecordsPerctGamesBehindViews { get; set; }
        public virtual DbSet<AllTeamRecordsPerctView> AllTeamRecordsPerctViews { get; set; }
        public virtual DbSet<AllGamesView> AllGamesViews { get; set; }


        private void FixEfProviderServicesProblem()
        {
            var instance = System.Data.Entity.SqlServer.SqlProviderServices.Instance;
        }

    }
}
