//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StadiumSurfaceCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StadiumSurfaceCode()
        {
            this.Stadia = new HashSet<Stadium>();
        }
    
        public int StadiumSurfaceCodeId { get; set; }
        public string StadiumSurfaceCode1 { get; set; }
        public string SurfaceName { get; set; }
        public System.DateTime StartDt { get; set; }
        public Nullable<System.DateTime> EndDt { get; set; }
        public string mod_usr { get; set; }
        public System.DateTime mod_date { get; set; }
        public string SportTypeGroupCode { get; set; }
    
        public virtual SportTypeGroup SportTypeGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stadium> Stadia { get; set; }
    }
}
