//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stadium
    {
        public int StadiumId { get; set; }
        public int AddressId { get; set; }
        public string StadiumName { get; set; }
        public int StadiumSurfaceCodeId { get; set; }
        public System.DateTime StartDt { get; set; }
        public Nullable<System.DateTime> EndDt { get; set; }
        public string mod_usr { get; set; }
        public Nullable<System.DateTime> mod_date { get; set; }
        public string SportTypeGroupCode { get; set; }
    
        public virtual StadiumSurfaceCode StadiumSurfaceCode { get; set; }
    }
}
